# Default values for terraform-operator.

# controller - vars for deployment and service of the server
controller:
  # controller.enabled -- deploy the terraform-operator controller
  enabled: true

  # controller.replicaCount -- number of replicas
  replicaCount: 1

  image:
    # controller.image.repository -- repo name without the tag. The init container shares the name
    # and appends `-gencert`.
    repository: isaaguilar/terraform-operator
    # controller.image.tag -- tag of the image
    tag: v0.9.0-pre3
    # controller.image.pullPolicy -- Set how kubernetes determines when
    # to pull the docker image.
    pullPolicy: IfNotPresent

  # controller.args -- additional arguments for the command
  # @default -- <a href="values.yaml#L23-L25">values.yaml</a>
  args:
  - --zap-log-level=debug
  - --zap-encoder=console
  ## Uncomment the following to allow the controller to create multiple threads
  ## when workflow pods get queued.
  # - --max-concurrent-reconciles=10

  # controller.resources -- CPU/Memory request and limit configuration
  # @default -- <a href="values.yaml#L32-L38">values.yaml</a>
  resources:
    limits:
      cpu: 50m
      memory: 128M
    requests:
      cpu: 25m
      memory: 64M

  # controller.environmentVars -- key/value envs
  environmentVars: {}

  # controller.nodeSelector -- node labels for pod assignment
  nodeSelector: {}

  # controller.tolerations -- List of node taints to tolerate
  tolerations: []

  # controller.affinity -- node/pod affinities
  affinity: {}

# - webhooks options
webhook:
  # -- enables the webhook - required most of the time
  enabled: true
